### ISSUE TITLE
Allow building as a relocatable library

### ISSUE THREAD

**Issue by onox** [ada-game-framework/sdlada#43]
I have a library project .gpr file that `with "sdlada"`. If sdlada is built as a static library then I get the following error: `cannot import static library project "sdlada"`.

If I change `Library_Kind` in `build/gnat/sdlada.gpr` to "relocatable", then the error disappears.

**Comment by Lucretia** [comment]
Is this still an issue, I removed the relocatable build ages ago in favour of just having a static build to reduce the number of libs people would need to distribute if they were to distribute their app/game binary only.

**Comment by onox** [comment]
No longer an issue
